### ISSUE TITLE
Replace: 

### ISSUE THREAD

**Issue by sentarokun** [iptv-org/iptv#6238] opened 2022-01-29 16:17 UTC
### Channel Name

Any channel from IP 50.7.74.29

### What happened to the stream?

It is disappeared from the playlist

### Playlist

jp.m3u

### Notes

Streams from 50.7.74.29 are unreachable

**Comment by Dum4G** [comment] 2022-01-30 08:55
Duplicate of https://github.com/iptv-org/iptv/issues/6224

We are well aware of that

**Closed by Dum4G** 2022-01-30 08:55 UTC
Labels: broken stream
