### ISSUE TITLE
Add: Antena 3 [RO]

### ISSUE THREAD

**Issue by DJ1999-max** [iptv-org/iptv#12556] opened 2023-04-25 18:03 UTC
### Channel ID

Antena3.ro

### Stream URL (optional)

https://rundle.deta.dev/hls/LIVE$Antena3/6.m3u8/Level(19012010)?start=LIVE&end=END

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-04-25 21:15
Duplicate of #11018

**Closed by freearhey** 2023-04-25 21:15 UTC
Labels: channel request, RO, rejected:duplicate
