### ISSUE TITLE
Add: TV Osaka

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#13016] opened 2023-05-29 01:01 UTC
### Channel ID

TVOsaka.jp

### Stream URL (optional)

https://iptv-org.github.io/iptv/countries/jp.m3u

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-05-29 05:11
Duplicate of #13014

**Closed by freearhey** 2023-05-29 05:11 UTC
Labels: channel request
