### ISSUE TITLE
Add: JOCX-DTV

### ISSUE THREAD

**Issue by solo489** [iptv-org/iptv#13718] opened 2023-08-04 03:40 UTC
### Channel ID

JOCX-DTV.jp

### Stream URL (optional)

https://redlabmcdn.s.llnwi.net/nv02/ryowa7hd/index.mpd

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-08-04 04:02
Duplicate of #13717

**Closed by freearhey** 2023-08-04 04:02 UTC
Labels: channel request
