### ISSUE TITLE
Add: Canal 12 [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10444] opened 2022-11-20 09:56 UTC
### Channel ID

Canal12.co

### Stream URL

https://edge.teveo.com.co/live/AeAAAgAJAAFFA1IAyADIQCAAAAAAAAAAAmN5-VqwVnhmAAAA/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment] 2022-11-20 18:57
I suppose you're referring to Canal 12 (Ciudad de Valledupar) : https://q-s-l4n3sh4d0w-usw.onrender.com/iptv-query?streaming-ip=https://teveo.com.co/player/AcAAAgAJAAFFA1IAyADIQCAAAAAAAAAA.js

**Comment by AntiPontifex** [comment] 2022-11-23 04:57
Duplicate of #9799: please close.

**Closed** 2022-11-23 06:28 UTC
Labels: channel request, CO, valid stream proposal
