### ISSUE TITLE
Request kurdish TV Channel

### ISSUE THREAD

**Issue by hawrazsabr** [iptv-org/iptv#1549] opened 2020-06-27 13:42 UTC
Country of the channel:
Iraq

Channel Name:
Iraqia Kurdish
WAAR TV HD
Korek TV
NRT TV HD
Kurdsat News HD
Ava Media TV
Kurd Channel TV
NRT 4

Channel Language:
Kurdish

Additional Information (optional):
Please add these channels.🤗

**Comment by themak1985** [comment] 2020-07-07 03:33
@hawrazsabr once is enough.
@freearhey this is a duplicate of #1498 #1511 - you can close those if you would like.

**Comment by hawrazsabr** [comment] 2020-07-07 10:49
@themak1985 you right, i deleted #1511
Thanks.

**Closed** 2020-07-07 14:24 UTC
Labels: IQ, channel request
