### ISSUE TITLE
Add: teen nick east

### ISSUE THREAD

**Issue by whyiyeet** [iptv-org/iptv#13385] opened 2023-06-28 01:17 UTC
### Channel ID

TeenNickEast.us

### Notes (optional)

im in wisconsin and i wanna watch episodes of henry danger

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-06-28 09:51
Duplicate of #7076

**Closed by freearhey** 2023-06-28 09:51 UTC
Labels: channel request
