### ISSUE TITLE
Add: Bangladesh 

### ISSUE THREAD

**Issue by Terolil** [iptv-org/iptv#15043] opened 2023-11-15 05:54 UTC
### Channel ID (required)

Tsports.bd

### Channel Name

T Sports 

### Stream URL (required)

http://otv.ftpbd.net:8082/T-Sports-HD/tracks-v1a1/mono.m3u8?token=837d6cde2dfde582d330b904d85a710f26bf0579-2ed99eed96e9fb2be53c7421c6eeeb4e-1699700331-1699689531

### Quality

1080p

### Label

None

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by freearhey** [comment] 2023-11-15 07:37
Duplicate of #15044

**Closed by freearhey** 2023-11-15 07:37 UTC
Labels: streams:add
