### ISSUE TITLE
Add: RTS [EC]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10423] opened 2022-11-19 12:30 UTC
### Channel ID

RTS.ec

### Stream URL

https://d6op0qag07k4o.cloudfront.net/hls/rts.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 01:58
Duplicate of #10047; please close.

**Closed** 2022-11-24 20:43 UTC
Labels: channel request
