### ISSUE TITLE
Add: NTN24 [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#11427] opened 2023-01-25 08:26 UTC
### Channel ID

NTN24.co

### Stream URL

http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/NTN24vivo

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Toei79** [comment] 2023-01-29 16:58
private video now.

**Comment by BellezaEmporium** [comment] 2023-02-11 22:50
Only available through the website. Might need an additional referer.

**Comment by BellezaEmporium** [comment] 2023-02-11 22:53
https://www.dailymotion.com/player/metadata/video/x7w4okl?embedder=https%3A%2F%2Fwww.ntn24.com&is_native_app=0 this works as an exampel.

**Comment by Toei79** [comment] 2023-04-08 03:00
there examples on playlists? how you add other referer, i checking playlists here like example by now

**Comment by BellezaEmporium** [comment] 2023-04-08 08:57
> there examples on playlists? how you add other referer, i checking playlists here like example by now

Precise your thoughts, as I'm not sure to have totally understood your question.

**Comment by freearhey** [comment] 2023-04-15 22:14
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/NTN24vivo (offline)

**Comment by azgaresncf** [comment] 2023-05-28 19:30
well, we just have to grab the m3u8 url, I think I will add it to my repo [strm2hls](https://github.com/azgaresncf/strm2hls) after

**Comment by BellezaEmporium** [comment] 2023-05-29 10:48
> well, we just have to grab the m3u8 url, I think I will add it to my repo [strm2hls](https://github.com/azgaresncf/strm2hls) after

You may also add a proxy support, as some streams are blocked by Daily, but once you get access to the main m3u file, you actually can watch those channels outside of the region the stream was intended for.

Ex : RCN [CO]

With VPN located in Bogota :
![image](https://github.com/iptv-org/iptv/assets/30985701/47de4d18-eafd-4980-858d-e68a9c8a6557)

Data : 

#EXTM3U
#EXT-X-STREAM-INF:RESOLUTION=848x477,FRAME-RATE=29.970030,BANDWIDTH=1359872,CODECS="avc1.64001f,mp4a.40.2",NAME="480"
https://stream-04.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-2.m3u8#cell=lnyc
#EXT-X-STREAM-INF:RESOLUTION=848x477,FRAME-RATE=29.970030,BANDWIDTH=1359872,CODECS="avc1.64001f,mp4a.40.2",NAME="480"
https://stream-03.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-2.m3u8#cell=lnyc
#EXT-X-STREAM-INF:RESOLUTION=320x180,FRAME-RATE=29.970030,BANDWIDTH=475136,CODECS="avc1.42000d,mp4a.40.5",NAME="240"
https://stream-04.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-0.m3u8#cell=lnyc
#EXT-X-STREAM-INF:RESOLUTION=320x180,FRAME-RATE=29.970030,BANDWIDTH=475136,CODECS="avc1.42000d,mp4a.40.5",NAME="240"
https://stream-03.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-0.m3u8#cell=lnyc
#EXT-X-STREAM-INF:RESOLUTION=512x288,FRAME-RATE=29.970030,BANDWIDTH=782336,CODECS="avc1.420015,mp4a.40.5",NAME="380"
https://stream-04.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-1.m3u8#cell=lnyc
#EXT-X-STREAM-INF:RESOLUTION=512x288,FRAME-RATE=29.970030,BANDWIDTH=782336,CODECS="avc1.420015,mp4a.40.5",NAME="380"
https://stream-03.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-1.m3u8#cell=lnyc
#EXT-X-STREAM-INF:RESOLUTION=1280x720,FRAME-RATE=29.970030,BANDWIDTH=2179072,CODECS="avc1.64001f,mp4a.40.2",NAME="720"
https://stream-04.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-3.m3u8#cell=lnyc
#EXT-X-STREAM-INF:RESOLUTION=1280x720,FRAME-RATE=29.970030,BANDWIDTH=2179072,CODECS="avc1.64001f,mp4a.40.2",NAME="720"
https://stream-03.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-3.m3u8#cell=lnyc


Without VPN (France)

![image](https://github.com/iptv-org/iptv/assets/30985701/e1ba5e99-77c4-4a98-a696-ea75e656262d)

**Comment by azgaresncf** [comment] 2023-05-29 12:13
thank you, that is a really good idea!

> > well, we just have to grab the m3u8 url, I think I will add it to my repo [strm2hls](https://github.com/azgaresncf/strm2hls) after
> 
> You may also add a proxy support, as some streams are blocked by Daily, but once you get access to the main m3u file, you actually can watch those channels outside of the region the stream was intended for.
> 
> Ex : RCN [CO]
> 
> With VPN located in Bogota : ![image](https://user-images.githubusercontent.com/30985701/241714208-47de4d18-eafd-4980-858d-e68a9c8a6557.png)
> 
> Data :
> 
> ```
> #EXTM3U
> #EXT-X-STREAM-INF:RESOLUTION=848x477,FRAME-RATE=29.970030,BANDWIDTH=1359872,CODECS="avc1.64001f,mp4a.40.2",NAME="480"
> https://stream-04.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-2.m3u8#cell=lnyc
> #EXT-X-STREAM-INF:RESOLUTION=848x477,FRAME-RATE=29.970030,BANDWIDTH=1359872,CODECS="avc1.64001f,mp4a.40.2",NAME="480"
> https://stream-03.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-2.m3u8#cell=lnyc
> #EXT-X-STREAM-INF:RESOLUTION=320x180,FRAME-RATE=29.970030,BANDWIDTH=475136,CODECS="avc1.42000d,mp4a.40.5",NAME="240"
> https://stream-04.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-0.m3u8#cell=lnyc
> #EXT-X-STREAM-INF:RESOLUTION=320x180,FRAME-RATE=29.970030,BANDWIDTH=475136,CODECS="avc1.42000d,mp4a.40.5",NAME="240"
> https://stream-03.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-0.m3u8#cell=lnyc
> #EXT-X-STREAM-INF:RESOLUTION=512x288,FRAME-RATE=29.970030,BANDWIDTH=782336,CODECS="avc1.420015,mp4a.40.5",NAME="380"
> https://stream-04.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-1.m3u8#cell=lnyc
> #EXT-X-STREAM-INF:RESOLUTION=512x288,FRAME-RATE=29.970030,BANDWIDTH=782336,CODECS="avc1.420015,mp4a.40.5",NAME="380"
> https://stream-03.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-1.m3u8#cell=lnyc
> #EXT-X-STREAM-INF:RESOLUTION=1280x720,FRAME-RATE=29.970030,BANDWIDTH=2179072,CODECS="avc1.64001f,mp4a.40.2",NAME="720"
> https://stream-04.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-3.m3u8#cell=lnyc
> #EXT-X-STREAM-INF:RESOLUTION=1280x720,FRAME-RATE=29.970030,BANDWIDTH=2179072,CODECS="avc1.64001f,mp4a.40.2",NAME="720"
> https://stream-03.nyc.dailymotion.com/sec(RTXUFuzJRHwPimV0dxTfPxlxluXanTTfN-UUJ6LmVT7MzjQGcLI5K8qv9oxVSqQDJksewILQV8LGKKE9Q7zfh9vWoFncrAdnEJQemReO4Is)/cloud/3/x7vyv0z/s/live-3.m3u8#cell=lnyc
> ```
> 
> Without VPN (France)
> 
> ![image](https://user-images.githubusercontent.com/30985701/241714387-e1ba5e99-77c4-4a98-a696-ea75e656262d.png)

**Comment by azgaresncf** [comment] 2023-05-29 12:14
j'pensais pas qu'il le bloquait en France par contre :')

**Comment by BellezaEmporium** [comment] 2023-05-29 15:22
> j'pensais pas qu'il le bloquait en France par contre :')

C'est assez commun que certains streams soient bloqués sur Daily, du moins, c'est celui qui l'affiche explicitement, même dans les documentations. YouTube est plus discret là dessus.

**Comment by azgaresncf** [comment] 2023-05-29 15:25
> > j'pensais pas qu'il le bloquait en France par contre :')
> 
> C'est assez commun que certains streams soient bloqués sur Daily, du moins, c'est celui qui l'affiche explicitement, même dans les documentations. YouTube est plus discret là dessus.

Merci de m'avoir mis au courant de ça en tout cas, c'est vrai que j'y avais pas forcément pensé.

**Comment by azgaresncf** [comment] 2023-05-29 18:37
Comme pour les liens Twitch, je compte faire une V2 de mon repo

**Comment by freearhey** [comment] 2023-05-31 04:17
Closed in favor of #12976

**Closed by freearhey** 2023-05-31 04:17 UTC
Labels: channel request, CO

**Comment by azgaresncf** [comment] 2023-05-31 06:08
https://www.dailymotion.com/player/metadata/video/x7w4okl?embedder=https%3A%2F%2Fwww.ntn24.com%2F&geo=1&player-id=xd8pw&locale=fr&dmV1st=bffe8e32-2a38-4353-88e3-a5ed574bd46b&dmTs=790845&is_native_app=0
