### ISSUE TITLE
Add: Iglgroup Tv

### ISSUE THREAD

**Issue by Iglgroupplay** [iptv-org/iptv#16350] opened 2024-04-10 15:54 UTC
### Channel ID (required)

IglgroupTv.ar

### Channel Name

IglgroupTv

### Stream URL (required)

https://vd01.streaminghd.net.ar:3049/hybrid/play.m3u8

### Quality

720p

### Label

None

### Notes

IglgroupTv 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by BellezaEmporium** [comment] 2024-04-10 19:12
Duplicate of https://github.com/iptv-org/iptv/issues/16329

**Closed by BellezaEmporium** 2024-04-10 19:12 UTC
Labels: streams:add

**Comment by Iglgroupplay** [comment] 2024-04-13 15:41
@BellezaEmporium  Quien me debe aprovar el Url..

**Comment by Iglgroupplay** [comment] 2024-04-28 22:41
#16350 Update

**Comment by BellezaEmporium** [comment] 2024-04-29 14:52
![image](https://github.com/iptv-org/iptv/assets/30985701/6578c967-e592-415e-8960-10e7601f22dd)
Still image right now.

**Comment by Iglgroupplay** [comment] 2024-04-29 16:12
Stream en Linea

**Comment by BellezaEmporium** [comment] 2024-04-29 19:27
Indeed, works now.

**Comment by Iglgroupplay** [comment] 2024-04-29 20:18
@BellezaEmporium Who else should approve so that it appears on the IPTV list (.ar)

**Comment by BellezaEmporium** [comment] 2024-04-29 20:20
It's all good, once it's closed it's on.
