### ISSUE TITLE
Add: Telemax [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10269] opened 2022-11-12 12:47 UTC
### Channel ID

Telemax.gt

### Stream URL

https://cdn.streamhispanatv.net:3824/live/telemaxlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 00:33
Duplicate of #10091; please close.

**Closed** 2022-12-21 19:17 UTC
Labels: channel request, valid stream proposal, GT
