### ISSUE TITLE
CNBC (USA)

### ISSUE THREAD

**Issue by chris202020202020** [iptv-org/iptv#13968] opened 2023-08-19 21:07 UTC
### Channel ID

CNBC.us

### Notes (optional)

add m3u link for cnbc (USA)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-09-06 13:37
Duplicate of https://github.com/iptv-org/iptv-org.github.io/issues/975

**Closed by freearhey** 2023-09-06 13:37 UTC
Labels: channel request, US
