### ISSUE TITLE
Replace: 

### ISSUE THREAD

**Issue by ChopperTom** [iptv-org/iptv#6152] opened 2022-01-21 06:16 UTC
### Channel Name

Fox News Channel

### What happened to the stream?

It is buffering to unplayable point

### Playlist

http://encodercdn1.frontline.ca/encoder181/output/FOX_News_720p/playlist.m3u8

### Notes

This issue started more than 2 weeks ago

**Comment by Dum4G** [comment] 2022-01-21 07:07
Duplicate of https://github.com/iptv-org/iptv/issues/6054

**Closed by Dum4G** 2022-01-21 07:07 UTC
Labels: broken stream
