### ISSUE TITLE
Add: Fort Tv 

### ISSUE THREAD

**Issue by OscarAteenyi** [iptv-org/iptv#7032] opened 2022-04-11 07:14 UTC
### Channel Name

Fort Tv 

### Channel ID

Fort Tv . Uganda

### Website

https://www.lyngsat-stream.com/tvchannels/ug/Fort-TV.html

### Stream URL

http://fort.co-works.org:8080/hls/live.stream.m3u8

### Notes

Fort Tv is a Ugandan Entertainment tv channel. It's stationed in the western part of the country in Fort portal tourism city. It's available on Lyngsat Stream and they have an app on Google play store. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment] 2022-04-11 15:48
Duplicate of #6871

**Closed by LaneSh4d0w** 2022-04-11 15:48 UTC
Labels: channel request

**Comment by OscarAteenyi** [comment] 2022-04-11 16:08
Does this mean we can now load and watch the Channel. Is it added?

**Comment by LaneSh4d0w** [comment] 2022-04-11 16:11
> Does this mean we can now load and watch the Channel. Is it added?

It hasn't been added, it is just that we are aware we already have been proposed this channel. Making more than one issue for it is counter-productive.
