### ISSUE TITLE
Animax 

### ISSUE THREAD

**Issue by Johelectrix09** [iptv-org/iptv#5639] opened 2021-12-09 07:17 UTC
**_Animax (English sub) :_** xxx
**_Japan:_** xxx
**_ (from playlist):_** xxx
**_Possible Replacement (optional):_** xxx
**_Why is it rarely playing and now it becomes unavailable _** xxx

**Comment by Dum4G** [comment] 2021-12-09 10:45
Duplicate of #5524

**Closed by Dum4G** 2021-12-09 10:45 UTC
Labels: broken stream
