### ISSUE TITLE
IPTV VIDEO CANNOT DEVELOP ON VLC

### ISSUE THREAD

**Issue by Alantienviet** [iptv-org/iptv#4681] opened 2021-09-23 18:00 UTC
### Discussed in https://github.com/iptv-org/iptv/discussions/4679

<div type='discussions-op-text'>

<sup>Originally posted by **Alantienviet** September 24, 2021</sup>
i have a link this works 100% well...but it can't play on VLC...can someone help me
this is my m3u path but it doesn't work on VLC but works fine on IPTV Lite android

#EXTINF:-1 tvg-id="sctv14hd" group-title="SCTV" "http://vthanh.live/ic/80.png", SCTV14 HD
https://e1.endpoint.cdn.sctvonline.vn/secure/sctv14/sd1/index.m3u8?md5=bs-8dgbSHwp63TDXoCpnkw&expires=2556118740

here is the homepage: https://sctvonline.vn/page/truyen-hinh-ecb1ec92</div>

**Comment by taodicakhia** [comment] 2021-09-24 03:25
Requires referrer

**Comment by Dum4G** [comment] 2021-09-24 04:11
Duplicate of #4679

**Closed by Dum4G** 2021-09-24 04:12 UTC
