### ISSUE TITLE
Add: Animax (JPN)

### ISSUE THREAD

**Issue by chris202020202020** [iptv-org/iptv#13971] opened 2023-08-19 21:12 UTC
### Channel ID

Animax.jp

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-09-06 14:16
Duplicate of #12217

**Closed by freearhey** 2023-09-06 14:16 UTC
Labels: channel request, JP
