### ISSUE TITLE
Broken: Fox News Channel

### ISSUE THREAD

**Issue by Kristal9** [iptv-org/iptv#7510] opened 2022-06-14 10:17 UTC
### Stream Title

Fox News Channel (720p)

### What happened to the stream?

Not loading

### Notes

This channel doesn't work. Fix it, please.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by LaneSh4d0w** [comment] 2022-06-14 15:55
makes allusion / dupe of #7118

**Closed by LaneSh4d0w** 2022-06-14 15:55 UTC
Labels: 🛠 broken stream
