### ISSUE TITLE
Replace: 

### ISSUE THREAD

**Issue by Sophgirl41** [iptv-org/iptv#5853] opened 2021-12-23 12:29 UTC
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

Rewind TV US (WPIXDT4) NY 

### What happened to the stream?

It is buffering to unplayable point

### Playlist

https://v-ny.mybtv.net/event/565/640x480.m3u8?start_time=2021-05-16T23%3A45%3A00%2B00%3A00&end_time=2028-05-17T05%3A00%3A00%2B00%3A00&env=prd

### Broken Link

Rewind TV US (WPIXDT4) NY 

### Possible Replacement

Rewind TV US (WPIXDT4) NY 

### Notes

When will the stream be fixed

**Comment by Dum4G** [comment] 2021-12-23 16:25
Duplicate of https://github.com/iptv-org/iptv/issues/5811

**Closed by Dum4G** 2021-12-23 16:25 UTC
Labels: broken stream
