### ISSUE TITLE
Add: Canal Capital [CO]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10421] opened 2022-11-19 11:47 UTC
### Channel ID

CanalCapital.co

### Stream URL

https://play.cdn.enetres.net/C99D9A0676F3401589C768D47D31605C021/021/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 04:03
Duplicate of #9906: please close.

**Closed** 2022-11-25 11:33 UTC
Labels: channel request, CO, valid stream proposal
