### ISSUE TITLE
Add: NHK World Premium [JP]

### ISSUE THREAD

**Issue by ZXArkin** [iptv-org/iptv#11084] opened 2023-01-01 22:24 UTC
### Channel ID

NHKWorldPremium.jp

### Stream URL

https://nhkwlive-pre-in.webcdn.stream.ne.jp/hls/live/nhkwlive-pre/index_1M.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2023-01-02 02:06
Thank you for the stream: it will be included in the next release.

**Comment by freearhey** [comment] 2023-04-15 10:14
Duplicate of #10955

**Closed by freearhey** 2023-04-15 10:14 UTC
Labels: channel request
