### ISSUE TITLE
Azam sports please

### ISSUE THREAD

**Issue by ahmedzooo** [iptv-org/iptv#4675] opened 2021-09-23 13:58 UTC
**Channel Name:** Azam sports 2
**Country:** Tanzania
**Language:** Swahili
**Website:** xxx
**Stream URL (optional):** https://1521034005.rsc.cdn77.org/1521034005/Manifest.mpd
**Notes (optional):** xxx

**Comment by Dum4G** [comment] 2021-09-23 14:01
To be accepted a link should play in VLC
Duplicate of https://github.com/iptv-org/iptv/discussions/4667

**Closed by Dum4G** 2021-09-23 14:01 UTC
Labels: channel request

**Comment by ahmedzooo** [comment] 2021-09-23 14:09
Play on pot player

**Comment by ahmedzooo** [comment] 2021-09-23 14:11
> To be accepted a link should play in VLC
> Duplicate of #4667

Play on pot player
