### ISSUE TITLE
Add: MSNBC (USA)

### ISSUE THREAD

**Issue by chris202020202020** [iptv-org/iptv#13969] opened 2023-08-19 21:08 UTC
### Channel ID

MSNBC.us

### Notes (optional)

please add m3u link for msnbc (USA)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-09-06 13:39
Duplicate of https://github.com/iptv-org/iptv-org.github.io/issues/505

**Closed by freearhey** 2023-09-06 13:39 UTC
Labels: channel request, US
