### ISSUE TITLE
Add: Sarapiqui TV [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10308] opened 2022-11-13 11:47 UTC
### Channel ID

SarapiquiTV.cr

### Stream URL

https://lstv.duckdns.org:449/hls/stv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 03:30
Duplicate of #9923: please close.

**Closed** 2022-11-24 20:49 UTC
Labels: channel request
