### ISSUE TITLE
Tallahassee Locals

### ISSUE THREAD

**Issue by Gitbone94** [iptv-org/iptv#9132] opened 2022-09-28 13:52 UTC
### Broken Link

https://5e6cea03e25b6.streamlock.net/live/WCTVDT2.stream/playlist.m3u8

### What happened to the stream?

Not loading

### Notes

The Tallahassee locals remain in the IPTV-ORG playlist but have not worked for months. It was mentioned in one of my previous issues when I was searching for MeTV channels that the team intended to bring it back. Any chance this is still going to happen?

https://5e6cea03e25b6.streamlock.net/live/WTXLHD.stream/playlist.m3u8
https://5e6cea03e25b6.streamlock.net/live/WCTVDT.stream/playlist.m3u8
https://5e6cea03e25b6.streamlock.net/live/WTWC-FX.stream/playlist.m3u8
https://5e6cea03e25b6.streamlock.net/live/WTWC-NB.stream/playlist.m3u8
https://5e6cea03e25b6.streamlock.net/live/WTLHCW.stream/playlist.m3u8
https://5e6cea03e25b6.streamlock.net/live/WCTVDT2.stream/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment] 2022-09-28 14:14
Duplicate of #7946

**Closed by freearhey** 2022-09-28 14:14 UTC
Labels: 🛠 broken stream
