### ISSUE TITLE
Replace: TF1.fr

### ISSUE THREAD

**Issue by jo-a11y** [iptv-org/iptv#11897] opened 2023-03-25 15:19 UTC
### Broken Link

https://tf1-hls-live-cdn1.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8

### What happened to the stream?

Not loading

### Notes

All the channels of the French group TF1 no longer work. (TF1, TMC, TFX, TF1 Films and Series)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment] 2023-03-26 00:21
You haven't checked the latest TF1 link that's on the playlists : https://live-tf1-hls-dai.cdn-1.diff.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8

**Comment by hijuuijj** [comment] 2023-03-26 17:37
> You haven't checked the latest TF1 link that's on the playlists : https://live-tf1-hls-dai.cdn-1.diff.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8

Where is that playlist? I can't find it here: [https://iptv-org.github.io/iptv/countries/fr.m3u](url)

**Comment by BellezaEmporium** [comment] 2023-03-26 19:38
https://raw.githubusercontent.com/iptv-org/iptv/master/streams/fr.m3u

**Comment by hijuuijj** [comment] 2023-03-26 21:17
> https://raw.githubusercontent.com/iptv-org/iptv/master/streams/fr.m3u

Thank you. Where is that playlist located? I only see 1 link anyway. (**TF1**, TMC, TFX, TF1 Films and Series)
I have these links but I don't know how to get the m3u8. I have some notions of PHP.

http://foofootv.com/tv/m3u8/fr/?id=tf1
http://foofootv.com/tv/m3u8/fr/?id=tfs
http://foofootv.com/tv/m3u8/fr/?id=tfx
http://foofootv.com/tv/m3u8/fr/?id=tmc
http://foofootv.com/tv/m3u8/fr/?id=lci

**Comment by BellezaEmporium** [comment] 2023-03-26 21:18
> > https://raw.githubusercontent.com/iptv-org/iptv/master/streams/fr.m3u
> 
> Thank you. Where is that playlist located? I only see 1 link anyway. (**TF1**, TMC, TFX, TF1 Films and Series)
> I have these links but I don't know how to get the m3u8. I have some notions of PHP.
> 
> http://foofootv.com/tv/m3u8/fr/?id=tf1
> http://foofootv.com/tv/m3u8/fr/?id=tfs
> http://foofootv.com/tv/m3u8/fr/?id=tfx
> http://foofootv.com/tv/m3u8/fr/?id=tmc
> http://foofootv.com/tv/m3u8/fr/?id=lci

Well yes, we are talking about TF1 here, and indeed this is one of the only links that work.

**Comment by freearhey** [comment] 2023-04-16 00:57
Duplicate of #11754

**Closed by freearhey** 2023-04-16 00:57 UTC
Labels: 🛠 broken stream, rejected:duplicate
