### ISSUE TITLE
Add: Full Channel [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10266] opened 2022-11-12 12:43 UTC
### Channel ID

FullChannel.gt

### Stream URL

https://cdn.streamhispanatv.net:3845/live/fullchannelgtlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 00:48
Duplicate of #10084; please close.

**Closed** 2022-11-24 21:09 UTC
Labels: channel request
