### ISSUE TITLE
Add: Teletoon

### ISSUE THREAD

**Issue by TheAGames10** [iptv-org/iptv#8036] opened 2022-08-13 19:33 UTC
### Channel Name

Teletoon English

### Channel ID

TeletoonEnglish.ca

### Website

Teletoon.ca (No actual live broadcast is found)

### Stream URL

xxx

### Notes

I really want to have a way to watch this in the future, but every link I have have found so far either does not work at all or is permanently offline.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment] 2022-08-14 21:57
Please verify if an issue was already available before adding a duplicate.

Duplicate of #7820

**Closed by LaneSh4d0w** 2022-08-14 21:57 UTC
Labels: channel request
