### ISSUE TITLE
Add: Barbe TV [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10263] opened 2022-11-12 12:38 UTC
### Channel ID

BarbeTV.gt

### Stream URL

https://cdn.streamhispanatv.net:3549/live/barbetvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 01:05
Duplicate of #10077; please close.

**Closed** 2022-11-24 21:10 UTC
Labels: channel request
