### ISSUE TITLE
Add: Boing Spain

### ISSUE THREAD

**Issue by SkylerDaKat** [iptv-org/iptv#13033] opened 2023-05-29 20:59 UTC
### Channel ID

BoingSpain.es

### Notes (optional)

I've been doing digging and found out Boing exists and I wanna bring it up since CN Spain is dead, replaying one video 24-7.
Boing is actually free to view but the only place you can get it anywhere for free is from the app but I think it lowers the quality by default??? I was wondering if anyone could extract the stream link? I tried doing it with PCAPandroid but I don't know what links are the stream link.
The stream is not geolocked from what I can tell, and it's basically cartoon network for Spanish people, anyways, just wanted to mention it.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-05-29 23:49
Duplicate of #12579

**Closed by freearhey** 2023-05-29 23:49 UTC
Labels: channel request
