### ISSUE TITLE
Make distinction between News and Local cast of WPVI / WPVI-DT1

### ISSUE THREAD

**Issue by steelerman34** [iptv-org/iptv#8934] opened 2022-09-21 18:38 UTC
### Broken Link

https://content.uplynk.com/channel/ext/10b98e7c615f43a98b180d51797e74aa/wpvi_24x7_news.m3u8

### What happened to the stream?

Other

### Possible Replacement

http://v-pi.theus6tv.duckdns.org/hls/6.1/playlist.m3u8

### Notes

For WPVIDT1.us, there are two streams listed, one the actual feed, the other just newscasts.  Please add back WPVI-DT1 mapping to the correct http://v-pi.theus6tv.duckdns.org/hls/6.1/playlist.m3u8 location.  This station is in the U.S. (PA) and should be in the appropriate playlists.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by MapGuy11** [comment] 2022-10-01 17:25
Duplicate of #8935

**Closed by MapGuy11** 2022-10-01 17:25 UTC
Labels: US, misidentified
