### ISSUE TITLE
Star Sports Select 2 HD

### ISSUE THREAD

**Issue by MonuMia1** [iptv-org/iptv#4743] opened 2021-09-26 04:16 UTC
Star Sports Select 2 HD m3u8 links please Thank You

**Channel Name:** Star Sports Select 2 HD
**Country:** INDIA
**Language:** English
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by LaneSh4d0w** [comment] 2021-09-27 10:46
Please look after already made issues before making a new one.

Duplicate of #1992 (channel was already been asked before)

**Closed by LaneSh4d0w** 2021-09-27 10:46 UTC
Labels: channel request, HK
