### ISSUE TITLE
Add: Disney Channel Poland

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#16857] opened 2024-06-24 11:10 UTC
### Channel ID (required)

DisneyChannel.pl

### Channel Name

Disney Channel Poland

### Stream URL (required)

http://185.236.229.62:9981/play/a07d

### Quality

1080p

### Label

None

### Notes

Completing request #16838

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by TestNintendo** [comment] 2024-06-26 08:27
Duplicate of #16838.

**Closed** 2024-06-28 22:09 UTC
Labels: streams:add
