### ISSUE TITLE
Add: super hungama

### ISSUE THREAD

**Issue by boi660** [iptv-org/iptv#6549] opened 2022-02-28 23:53 UTC
### Channel Name

super hungama

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment] 2022-03-01 10:30
Super Hungama is the new name for Marvel HQ. Since an demand for Marvel HQ was already issued, closing this.

Dupe of https://github.com/iptv-org/iptv/issues/6434

**Closed by LaneSh4d0w** 2022-03-01 10:30 UTC
Labels: channel request
