### ISSUE TITLE
Add: Disney XD Poland

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/iptv#16878] opened 2024-06-25 10:18 UTC
### Channel ID (required)

DisneyXD.pl

### Channel Name

Disney XD Poland

### Stream URL (required)

http://178.219.128.68:64888/DISNXD

### Quality

576p

### Label

None

### Notes

Submitting request #16841

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by TestNintendo** [comment] 2024-06-26 08:26
Duplicate of #16841.
Close the issue ASAP.

**Closed** 2024-06-28 22:09 UTC
Labels: streams:add
