### ISSUE TITLE
Add: Nicktoons [AF]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12573] opened 2023-04-26 00:18 UTC
### Channel ID

NicktoonsAfrica.za

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by dantheman121** [comment] 2023-04-26 00:33
@freearhey i added the right id go check

**Comment by freearhey** [comment] 2023-06-09 22:06
Duplicate of #12283

**Closed by freearhey** 2023-06-09 22:06 UTC
Labels: channel request, ZA
