### ISSUE TITLE
ADD: SPLTV

### ISSUE THREAD

**Issue by oussamame07** [iptv-org/iptv#10797] opened 2022-12-12 15:45 UTC
### Channel ID

spltv.tn

### Stream URL

https://livetest.spl-tv.com/hls/stream_higher/index.m3u8

### Notes

Site web : https://spl-tv.com/live-tv
email : contact@spl-tv.com

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by UltraHDR** [comment] 2022-12-21 01:11
Duplicate of #10901

**Closed by UltraHDR** 2022-12-21 01:11 UTC
Labels: channel request
