### ISSUE TITLE
add super hungama 

### ISSUE THREAD

**Issue by boi660** [iptv-org/iptv#6573] opened 2022-03-02 21:40 UTC
### Channel Name

super hungama

### Notes

add super humgama link vod

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by boi660** [comment] 2022-03-02 21:40
add this channel plz

**Comment by what-a** [comment] 2022-03-02 22:33
Duplicate of #6434

**Closed by what-a** 2022-03-02 22:33 UTC
Labels: channel request
