### ISSUE TITLE
Replace: FoxNewsChannel.us

### ISSUE THREAD

**Issue by mrIMSirius** [iptv-org/iptv#12078] opened 2023-04-06 17:27 UTC
### Broken Link

http://trn03.tulix.tv/AsEAeOtIxz/playlist.m3u8

### What happened to the stream?

Not loading

### Notes

403 Unauthorized
Streamer protection system doesn't allow you to watch this content.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by freearhey** [comment] 2023-04-16 01:01
Duplicate of #11702

**Closed by freearhey** 2023-04-16 01:01 UTC
Labels: 🛠 broken stream, rejected:duplicate
