### ISSUE TITLE
Add: AT-X (JPN)

### ISSUE THREAD

**Issue by chris202020202020** [iptv-org/iptv#13970] opened 2023-08-19 21:10 UTC
### Channel ID

ATX.jp

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-09-06 14:18
Duplicate of #13793

**Closed by freearhey** 2023-09-06 14:18 UTC
Labels: channel request, JP
