### ISSUE TITLE
Replace: ITV

### ISSUE THREAD

**Issue by bingit-dev** [iptv-org/iptv#12011] opened 2023-03-31 06:43 UTC
### Broken Link

https://cdnuk001.broadcastcdn.net/KUK-ITV-107/playlist.m3u8

### What happened to the stream?

Displays a message asking to renew subscription

### Possible Replacement

https://epg.pw/stream/92d1531ef1957f39601008d49b561e1c46f6e72eb1968612b0ee7bed414631bb.ctv

### Notes

It is a kapang stream I'm pretty sure because it pops up asking for it.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by BellezaEmporium** [comment] 2023-03-31 08:11
Redirects to a MuMuDVB service. Multicast service with multiple UK channels.

**Comment by bingit-dev** [comment] 2023-03-31 12:12
Apologies, I cannot find a new stream, can anyone get one?

**Comment by aarubui** [comment] 2023-04-08 07:45
Duplicate of #10493 and #10873, which provide a possible replacement.

**Closed** 2023-04-16 01:00 UTC
Labels: 🛠 broken stream, rejected:duplicate
