### ISSUE TITLE
Add: Azteca 7 | (MX)

### ISSUE THREAD

**Issue by R4IN2007** [iptv-org/iptv#8910] opened 2022-09-20 23:26 UTC
### Channel ID

Azteca7.mx

### Stream URL

https://mdstrm.com/live-stream-gdai/609ad46a7a441137107d7a81/linear/hls/pa/event/PNEbbcJZRAaP4wDlQMW2LA/stream/00bf1639-7ddc-4884-9697-d1ea6a9af90a:CHS/master.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by LaneSh4d0w** [comment] 2022-09-21 11:40
Same as the issues above.

https://mdstrm.com/live-stream-playlist/609ad46a7a441137107d7a81.m3u8 as an alternative.

**Comment by sguinetti** [comment] 2022-09-22 14:09
Azteca 7 was closed previously (#5847), because broadcasts delayed DFL games on Thurday days. Also duplicate of #6507, I guess.

**Comment by freearhey** [comment] 2022-09-22 23:57
Duplicate https://github.com/iptv-org/iptv/issues/6507

**Closed by freearhey** 2022-09-22 23:57 UTC
Labels: channel request, MX
