### ISSUE TITLE
New Irish Channels

### ISSUE THREAD

**Issue by 129612231-scripts** [iptv-org/iptv#3170] opened 2021-06-13 19:36 UTC
**Channel Name:** Virgin Media One
**Country:** Ireland (IE)
**Language:** English
**External Link (optional):** http://iptvnow.me:8080/dindin-3505/RAp0L4nWBm/1143.ts
**Notes (optional):** Stutters Sometimes

**Comment by LaneSh4d0w** [comment] 2021-06-13 20:55
Duplicate of #1966, closed in that favor.

**Closed by LaneSh4d0w** 2021-06-13 20:55 UTC
Labels: channel request

**Comment by 129612231-scripts** [comment] 2021-06-14 15:29
Yes, None of the channels there have been added.
