### ISSUE TITLE
Add: WABC-DT1

### ISSUE THREAD

**Issue by chammer977** [iptv-org/iptv#9231] opened 2022-10-01 15:07 UTC
### Channel ID

WABCDT1.us

### Notes

Hi

The attatched stream is for ABC NY local news, not WABC-DT1. If possible, please could you add the normal broadcast channel?

Thanks

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2022-10-01 16:42
Duplicate of #8935

**Comment by freearhey** [comment] 2022-10-02 07:29
Related #8935

**Comment by AntiPontifex** [comment] 2022-11-25 07:41
Dead issue: please close.

**Comment by freearhey** [comment] 2023-04-14 20:26
Closed in favor of #8935

**Closed by freearhey** 2023-04-14 20:26 UTC
Labels: channel request, US
