### ISSUE TITLE
Add: Tunevision [GT]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10272] opened 2022-11-12 12:55 UTC
### Channel ID

Tunevision.gt

### Stream URL

https://cdn.streamhispanatv.net:3852/live/tunevisionlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 00:28
Duplicate of #10093; will be included in future gt.m3u update. Please close.

**Closed** 2022-12-21 19:17 UTC
Labels: channel request, valid stream proposal, GT
