### ISSUE TITLE
Replace: All Japanese Channels Doesn't Work

### ISSUE THREAD

**Issue by Getze56901** [iptv-org/iptv#6001] opened 2022-01-06 00:07 UTC
### Channel Name

Animax Japan, AT-X, Fuji TV, TBS And More

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://iptv-org.github.io/iptv/countries/jp.m3u

**Comment by dedarmstrong** [comment] 2022-01-06 00:25
Thanks for copying me

**Comment by dedarmstrong** [comment] 2022-01-06 00:42
Though in all honesty I am happy I am not alone in having issues with japanese tv

**Comment by Dum4G** [comment] 2022-01-06 07:12
Duplicate of #5999

**Closed by Dum4G** 2022-01-06 07:12 UTC
Labels: broken stream

**Comment by Dum4G** [comment] 2022-01-06 07:13
We hear you loud and clear. We'll do our best to find an alternative (when and if possible tho)

**Comment by GiovanniSebastian** [comment] 2022-01-06 19:22
Token: 
http://50.7.74.29:8080/hlsok/j00038/index.m3u8?key=aIq61Ui88wXMJKhDr-0x-Q&expires=1641511091&mac=38:80:df:0f:e4:c6

**Comment by GiovanniSebastian** [comment] 2022-01-06 19:36
This link responds but don' work: http://50.7.74.29:8080/hlsok/j00038/index.ts
