### ISSUE TITLE
AsianetHD

### ISSUE THREAD

**Issue by shahinms1** [iptv-org/iptv#3518] opened 2021-07-11 16:35 UTC
**Channel Name:** AsianetHD
**Country:** India
**Language:** Malayalam
**Website:** https://en.m.wikipedia.org/wiki/Asianet_(TV_channel)
**Stream URL (optional):** xxx
**Notes (optional):** xxx

**Comment by Dum4G** [comment] 2021-08-01 09:03
#EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/en/3/33/Asianet%28TVchannel%29Logo.jpg" tvg-id="Asianet HD" group-title="Malayalam", Asianet HS HD
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (CrKey armv7l 1.4.15250) AppleWebKit/JioTV/537.36 (KAIOS, like Gecko) Chrome/74.0.3729.77 Safari/537.36
http://asianethd-i.akamaihd.net/hls/live/569828/asianethd/master.m3u8

Needs check from an Indian IP

**Comment by Dum4G** [comment] 2021-08-01 20:29
@LaneSh4d0w

**Comment by LaneSh4d0w** [comment] 2021-08-01 20:34
474 Unknown - Error while treating your request.

**Comment by ronybc** [comment] 2021-08-02 13:32
HTTP error 403 Forbidden
(accessed from Thiruvananthapuram, Kerala)

**Comment by Dum4G** [comment] 2021-08-02 13:44
> HTTP error 403 Forbidden
> (accessed from Thiruvananthapuram, Kerala)

Have you tried with EXTVLCOPT string?

**Comment by ronybc** [comment] 2021-08-02 13:59
No, how to do so?
I tried with mpv:

> $ mpv http://asianethd-i.akamaihd.net/hls/live/569828/asianethd/master.m3u8
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://asianethd-i.akamaihd.net/hls/live/569828/asianethd/master.m3u8.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytdl_hook] youtube-dl failed: unexpected error occurred

Python request:

> '<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;asianethd&#45;i&#46;akamaihd&#46;net&#47;hls&#47;live&#47;569828&#47;asianethd&#47;master&#46;m3u8" on this server.<P>\nReference&#32;&#35;18&#46;ce9eda17&#46;1627912557&#46;64c033f\n</BODY>\n</HTML>\n'

**Comment by Dum4G** [comment] 2021-08-02 14:03
> No, how to do so?

Just copy everything from my post into new m3u file and try to open in VLC

**Comment by ronybc** [comment] 2021-08-02 15:03
Copied it all to /tmp/asianet.m3u

> $ vlc /tmp/asianet.m3u 
VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
[000055fa35377630] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[00007f745c0016a0] access stream error: HTTP 403 error
[00007f745c0016a0] http stream error: error: HTTP/1.0 403 Forbidden
[00007f745c000fa0] access stream error: HTTP 403 error
[00007f745c000fa0] http stream error: error: HTTP/1.0 403 Forbidden
[00007f745c004370] access stream error: HTTP 403 error

**Comment by freearhey** [comment] 2021-08-04 20:18
Closed in favor #1934

**Closed by freearhey** 2021-08-04 20:18 UTC
Labels: IN, channel request
