### ISSUE TITLE
Add: MV Lao TV

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv#15662] opened 2024-01-25 12:07 UTC
### Channel ID (required)

MVLaoTV.la

### Stream URL (required)

https://n-edge-1-th.v2h-cdn.com/mvlao/mvlao/playlist.m3u8

### Quality

None

### Label

Geo-blocked

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by Dum4G** [comment] 2024-01-25 16:04
Duplicate of https://github.com/iptv-org/iptv/issues/15597

**Closed by Dum4G** 2024-01-25 16:04 UTC
Labels: rejected:duplicate, streams:add
