### ISSUE TITLE
Add: Pluto TV G4 Select

### ISSUE THREAD

**Issue by thoudankeykang** [iptv-org/iptv#6660] opened 2022-03-09 01:02 UTC
### Channel Name

Pluto TV G4 Select

### Website

https://pluto.tv

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by Lucas-mother3** [comment] 2022-03-09 07:06
#6643

**Comment by LaneSh4d0w** [comment] 2022-03-09 07:51
Duplicate of #6643.

**Closed by LaneSh4d0w** 2022-03-09 07:51 UTC
Labels: channel request
