### ISSUE TITLE
Add: TVC [EC]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10424] opened 2022-11-19 12:32 UTC
### Channel ID

TVC.ec

### Stream URL

https://d6op0qag07k4o.cloudfront.net/hls/tvc.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 01:55
Duplicate of #10049; please close.

**Closed** 2022-11-24 20:43 UTC
Labels: channel request
