### ISSUE TITLE
Add: Los Santos TV [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10304] opened 2022-11-13 11:34 UTC
### Channel ID

LosSantosTV.cr

### Stream URL

https://lstv.duckdns.org:449/hls/lstv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 03:47
Duplicate of #9915: please close.

**Closed** 2022-11-24 20:50 UTC
Labels: channel request
