### ISSUE TITLE
MBO HD

### ISSUE THREAD

**Issue by Manipulativemachan** [iptv-org/iptv#4707] opened 2021-09-24 19:05 UTC
**Channel Name:** MBO HD
**Country:** IN
**Language:** Malayalam
**Website:** xxx
**Stream URL (optional):** xxx
**Notes (optional):** available on mhdtvworld apk. Couldn't find the link.

**Comment by LaneSh4d0w** [comment] 2021-09-26 17:17
Please look at the already opened issues before posting a new one.

Duplicate of #4391

**Closed by LaneSh4d0w** 2021-09-26 17:17 UTC
Labels: channel request, IN
