### ISSUE TITLE
Add: Nickelodeon East

### ISSUE THREAD

**Issue by whyiyeet** [iptv-org/iptv#13384] opened 2023-06-28 01:11 UTC
### Channel ID

NickelodeonEast.us

### Notes (optional)

i am in wisconsin and wanna watch nickelodeon in the usa

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-06-28 09:51
Duplicate of #13035

**Closed by freearhey** 2023-06-28 09:51 UTC
Labels: channel request

**Comment by whyiyeet** [comment] 2023-06-28 13:03
jesus. if theres a duplicate you might need t do something
