### ISSUE TITLE
Add: Oldies Hits [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10306] opened 2022-11-13 11:40 UTC
### Channel ID

OldiesHits.cr

### Stream URL

https://video01.logicahost.com.br/oldieshits/oldieshits/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 03:38
Duplicate of #9919: please close.

**Closed** 2022-11-24 20:50 UTC
Labels: channel request
