### ISSUE TITLE
Add: Zaracay TV [EC]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10425] opened 2022-11-19 12:37 UTC
### Channel ID

ZaracayTV.ec

### Stream URL

https://streamingwowza.com:19360/zaracaytv/zaracaytv.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 01:35
Duplicate of #10053; please close.

**Closed** 2022-11-24 20:42 UTC
Labels: channel request
