### ISSUE TITLE
Add: Bang Bang [AL]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12583] opened 2023-04-26 00:49 UTC
### Channel ID

BangBang.al

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-06-09 22:06
Duplicate of #8170

**Closed by freearhey** 2023-06-09 22:06 UTC
Labels: channel request, AL
