### ISSUE TITLE
Replace: Cartoon Network Asia

### ISSUE THREAD

**Issue by boomboom4100** [iptv-org/iptv#11295] opened 2023-01-18 07:32 UTC
### Broken Link

http://198.16.106.62:8278/streams/d/Cn/playlist.m3u8

### What happened to the stream?

Not loading

### Notes

Cartoon Network Asia not loading. Found in PH playlist.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by AntiPontifex** [comment] 2023-01-19 22:22
Does not work (geo-blocked)?

**Comment by boomboom4100** [comment] 2023-01-20 04:08
> Does not work (geo-blocked)?

Hi! By any chance, do you know which country/region is able to access it? I'll try a bunch of VPNs later to find out.

**Comment by AntiPontifex** [comment] 2023-01-20 19:46
No, sorry I don't.

**Comment by LaneSh4d0w** [comment] 2023-01-21 13:37
Those links seem to be widely used for Malay streams. Not quite sure as this server is dead since some time.

**Comment by freearhey** [comment] 2023-04-16 00:53
Duplicate of #7661

**Closed by freearhey** 2023-04-16 00:53 UTC
Labels: 🛠 broken stream, rejected:duplicate
