### ISSUE TITLE
Add: Luz Naciente TV [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10305] opened 2022-11-13 11:36 UTC
### Channel ID

LuzNacienteTV.cr

### Stream URL

https://vdo.luznacientetv.com:3555/live/luznacientetvlive.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 03:46
Duplicate of #9916: please close.

**Closed** 2022-11-24 20:50 UTC
Labels: channel request
