### ISSUE TITLE
Japan IPTV cannot stream

### ISSUE THREAD

**Issue by Irfandnial99** [iptv-org/iptv#17864] opened 2024-10-26 02:22 UTC
Dear [IPTV Provider’s Support Team],

 XeI hope this message finds you well. I am experiencing an issue with several Japanese TV channels on my IPTV service. When attempting to stream, I receive a notification stating, “404 stream cannot be reached, please contact your provider.”

Could you kindly assist in resolving this issue at your earliest convenience? If there are any additional details

**Comment by freearhey** [comment] 2024-10-26 04:21
Duplicate of https://github.com/iptv-org/iptv/issues/17863

**Closed by freearhey** 2024-10-26 04:21 UTC

**Comment by chugor** [comment] 2024-11-04 08:32
what thats mean?
