### ISSUE TITLE
Add: TLC

### ISSUE THREAD

**Issue by jkemp814** [iptv-org/iptv#3359] opened 2021-07-01 23:54 UTC
**Channel Name:** TLC
**Country:** USA
**Language:** English
**External Link (optional):** [DMCA]
**Notes (optional):** Works in both VLC and FFplay

**Comment by Dum4G** [comment] 2021-07-01 23:58
Duplicate of https://github.com/iptv-org/iptv/issues/3350

**Closed by Dum4G** 2021-07-01 23:58 UTC
Labels: channel request, duplicate
