### ISSUE TITLE
Add: çufo [AL]

### ISSUE THREAD

**Issue by dantheman121** [iptv-org/iptv#12580] opened 2023-04-26 00:44 UTC
### Channel ID

Cufo.al

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-04-26 00:52
Duplicate of #8131

**Closed by freearhey** 2023-04-26 00:52 UTC
Labels: channel request, rejected:duplicate
