### ISSUE TITLE
Add: San Vito Television [CR]

### ISSUE THREAD

**Issue by Carlinhos027** [iptv-org/iptv#10307] opened 2022-11-13 11:46 UTC
### Channel ID

SanVitoTelevision.cr

### Stream URL

https://stmv.streamingvip.click/sanvitotv/sanvitotv/playlist.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by AntiPontifex** [comment] 2022-11-23 03:31
Duplicate of #9922: please close.

**Closed** 2022-11-24 20:50 UTC
Labels: channel request
