### ISSUE TITLE
Broken: Link

### ISSUE THREAD

**Issue by MrMussa** [iptv-org/iptv#12445] opened 2023-04-21 13:45 UTC
### Broken Link

https://expereiencersinternational.github.io/tvsetup/config

### What happened to the stream?

Not loading

### Notes (optional)

Channels not showing from the UK as at 07:25 UTC include, but are not
limited to:

KUK-ITV1
KUK-FOUR
KUK-FIVE
KUK-ITV1+1
KUK-ITV2
KUK-BBCNEWS
KUK-YESTERDAY
KUK-ITV3
KUK-ITV4
KUK-SKYNEWS
KUK-CBEEBIES
KUK-CBBC

Someone closed the previous issue claiming it was solved. The following is a screengrab of the station claimed to be working as at 13:43 UTC (Friday).
![Screenshot_20230421_163951_IPTV Player](https://user-images.githubusercontent.com/129394688/233651859-584024b6-fe0e-415d-89d4-f68557b59e81.jpg)
![Screenshot_20230421_125833_IPTV Player](https://user-images.githubusercontent.com/129394688/233651935-3f3f7b8d-2e72-4d1f-8069-873338b0202b.jpg)
![Screenshot_20230421_101917_IPTV Player](https://user-images.githubusercontent.com/129394688/233651941-10ef3f28-9fc6-46da-9e2c-87230fe80637.jpg)
![Screenshot_20230421_101904_IPTV Player](https://user-images.githubusercontent.com/129394688/233651951-77b5c2be-6995-4ca1-bc81-8696a3a4c4a3.jpg)
![Screenshot_20230421_101812_IPTV Player](https://user-images.githubusercontent.com/129394688/233651960-073c675f-7fa1-421f-a1ef-d81d0f0818c0.jpg)
![Screenshot_20230421_101757_IPTV Player](https://user-images.githubusercontent.com/129394688/233651974-56c49336-2979-4b71-9161-cc35466577c4.jpg)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

**Comment by MrMussa** [comment] 2023-04-21 13:47
![Screenshot_20230421_164653_IPTV Player](https://user-images.githubusercontent.com/129394688/233652380-cc6147dd-7dd6-4304-8f7b-1c7940e1b9ad.jpg)
![Screenshot_20230421_101711_IPTV Player](https://user-images.githubusercontent.com/129394688/233652466-71ed4e9b-34b3-4148-9a08-6124fdabd395.jpg)

**Comment by ExperiencersInternational** [comment] 2023-04-21 18:01
I'm not entirely sure what's happening here, since Really, Channel 4 +1, Quest, ITV3, More4 and ITV4 which uses the broadcastcdn links works fine.

Can't attach image for security reasons.

**Comment by MrMussa** [comment] 2023-04-21 18:43
Yes, they are working fine now. But there are still channels that are not
working properly. I will post them on github.

Thanks.

Mussa

**Comment by freearhey** [comment] 2023-04-22 00:51
Duplicate of #12444

**Closed by freearhey** 2023-04-22 00:51 UTC
Labels: 🛠 broken stream, rejected:duplicate

**Comment by MrMussa** [comment] 2023-04-22 07:58
It's not yet working, but I have opened a new issue on Github, right now.


Mussa
