### ISSUE TITLE
Add: REWIND TV

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/iptv#12332] opened 2023-04-15 13:06 UTC
### Channel ID

WPIXDT4.us

### Stream URL (optional)

https://v-ny.mybtv.net/live/565/640x480.m3u8

### Notes (optional)

The link is not working anymore. 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

**Comment by freearhey** [comment] 2023-04-15 13:14
Duplicate of #11113

**Closed by freearhey** 2023-04-15 13:14 UTC
Labels: channel request, rejected:duplicate
