### ISSUE TITLE
Replace: 

### ISSUE THREAD

**Issue by lntakahashi** [iptv-org/iptv#6066] opened 2022-01-13 18:20 UTC
### Channel Name

NHK G Tokyo

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://iptv-org.github.io/iptv/countries/jp.m3u

### Broken Link

http://50.7.74.29:8880/hls/j00033/index.m3u8

**Comment by Sphinxroot** [comment] 2022-01-14 05:37
duplicate of #6064

**Closed by Sphinxroot** 2022-01-14 05:37 UTC
Labels: broken stream
