### ISSUE TITLE
Close Channel Requests Within a Time Period

### ISSUE THREAD

**Issue by themak1985** [iptv-org/iptv#1856] opened 2020-12-28 06:40 UTC
**Is your feature request related to a problem? Please describe.**
We have about 100 issues submitted, mostly channel requests, some of them over a year old.

**Describe the solution you'd like**
I suggest closing channel requests that are not resolved within 30 days of the last comment or within 90 days of opening. 
Also, I suggest making channel requests limited and reasonable, such as no more than 5 channels per request unless also including links to streams.

**Additional context**
We would also want to update the readme.md file with this information.

**Comment by freearhey** [comment] 2021-01-14 17:41
@themak1985 I just updated all the issue templates and added a limit of one channel per issue to the readme.md. Hopefully this will make it easier to keep track of future requests.

As for closing old issues, I think your idea of grouping them by country before closing is the most appropriate in this case.

**Comment by themak1985** [comment] 2021-01-15 22:17
@freearhey I see you have been busy at work. 
I assume new channel requests should be made by creating a new issue and not by commenting in the new issues we (mostly you) created. :)

**Comment by freearhey** [comment] 2021-01-15 22:44
@themak1985 I personally do not care, as long as it is convenient for everyone to track requests. Maybe we can just put all new requests into the lists and close the issue immediately.

**Comment by freearhey** [comment] 2021-01-30 17:30
I believe the issue is resolved at this point. If necessary, we can reopen the issue at any time.

**Closed by freearhey** 2021-01-30 17:30 UTC
Labels: feature request
